version: '3.7'

services:
  nginx:
    build: .
    ports:
      - 1300:80
    volumes:
      - static_volume:/home/app/microservice/static
    depends_on:
      - web
    restart: "on-failure"
  web:
    build: . #build the image for the web service from the dockerfile in parent directory
    command: sh -c "
                    python manage.py collectstatic --noinput &&
                    gunicorn demodocker.wsgi:application --bind 0.0.0.0:${APP_PORT}"
    volumes:
      - .:/microservice:rw # map data and files from parent directory in host to microservice directory in docker containe
      - static_volume:/home/app/microservice/static
    env_file:
      - .env.prod
    image: demodocker

    expose:
      - 8000
    restart: "on-failure"
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data2/
    env_file:
      - .env.prod
    environment:
      - POSTGRES_PASSWORD=demodocker123
      - POSTGRES_DB=demodocker001
      - PGPORT=5432
      - POSTGRES_USER=demodocker
    restart: "on-failure"


volumes:
  postgres_data:
  static_volume: