FROM python:3.6

ENV PYTHONUNBUFFERED 1
RUN mkdir -p /opt/services/demodocker/src

COPY requirements.txt /opt/services/demodocker/src/

# install dependencies
RUN pip install --upgrade pip
WORKDIR /opt/services/demodocker/src
RUN pip install -r requirements.txt

COPY . /opt/services/demodocker/src
RUN python manage.py collectstatic --no-input

EXPOSE 4169
CMD ["gunicorn", "-c", "config/gunicorn/conf.py", "--bind", ":4169", "--chdir", "demodocker", "demodocker.wsgi:application"]
